import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NavigationEnd, Router, RouterLink, RouterLinkActive, RouterOutlet, Routes } from '@angular/router';
import { filter } from 'rxjs';
import { Api, Session } from './api.service';

@Component({ selector: 'app-root', standalone: true, imports: [RouterOutlet], template: '<router-outlet />' })
export class AppComponent {}

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, RouterLinkActive],
  template: `
<section class="hero" *ngIf="path === '/'">
  <div class="hero-box"><div class="eyebrow">Secure credit, beautifully managed</div><h1>Mosaic Vault</h1><p>Your trusted credit-card space—clear spending, smarter payments, and complete control in one secure portal.</p><div class="actions"><a class="btn" routerLink="/customer-signup">Create customer account</a><a class="btn alt" routerLink="/customer-login">Customer sign in</a><a class="btn alt" routerLink="/staff-login">Bank staff sign in</a></div></div>
</section>

<section class="page" *ngIf="path === '/staff-login' || path === '/customer-login'"><div class="card login"><div class="eyebrow">{{ path === '/staff-login' ? 'Mosaic Vault staff' : 'Mosaic Vault customer' }} access</div><h2>Welcome back</h2><div class="alert error" *ngIf="message">{{ message }}</div><label>{{ path === '/staff-login' ? 'Username' : 'Username or email' }}</label><input [(ngModel)]="username" autocomplete="username"><label>Password</label><input type="password" [(ngModel)]="password" autocomplete="current-password" (keyup.enter)="login()"><button class="btn" style="width:100%;margin-top:20px" (click)="login()">Sign in</button><p class="muted" *ngIf="path === '/staff-login'">Demo staff access: staff / Staff&#64;123</p><p class="muted" *ngIf="path === '/customer-login'">New bank customer? <a routerLink="/customer-signup">Create your online account</a></p><a routerLink="/">Back to welcome</a></div></section>

<section class="page" *ngIf="path === '/customer-signup'"><div class="card login"><div class="eyebrow">Mosaic Vault customer registration</div><h2>Create your online account</h2><p class="muted">Your name and email must match the customer profile created by bank staff.</p><div class="alert" *ngIf="message" [class.error]="error">{{ message }}</div><label>Full name</label><input [(ngModel)]="registration.name" autocomplete="name"><label>Email address</label><input type="email" [(ngModel)]="registration.email" autocomplete="email"><label>Choose username</label><input [(ngModel)]="registration.username" autocomplete="username"><label>Choose password</label><input type="password" [(ngModel)]="registration.password" autocomplete="new-password"><button class="btn" style="width:100%;margin-top:20px" (click)="signup()">Create account</button><p class="muted">Already registered? <a routerLink="/customer-login">Sign in</a></p><a routerLink="/">Back to welcome</a></div></section>

<div class="shell" *ngIf="isPortal">
  <header class="top"><a class="brand" routerLink="/">Mosaic Vault</a>
    <nav class="nav" *ngIf="session?.role === 'STAFF'"><a routerLink="/staff-dashboard" routerLinkActive="active">Dashboard</a><a routerLink="/customers" routerLinkActive="active">Customers</a><a routerLink="/cards" routerLinkActive="active">Credit Cards</a><a routerLink="/merchants" routerLinkActive="active">Merchants</a><a routerLink="/transactions" routerLinkActive="active">Transactions</a></nav>
    <nav class="nav" *ngIf="session?.role === 'CUSTOMER'"><a routerLink="/customer-dashboard" routerLinkActive="active">Dashboard</a><a routerLink="/my-cards" routerLinkActive="active">My Cards</a><a routerLink="/purchase" routerLinkActive="active">Make Purchase</a><a routerLink="/payment" routerLinkActive="active">Pay Bill</a><a routerLink="/my-transactions" routerLinkActive="active">My Transactions</a><a routerLink="/statements" routerLinkActive="active">Statements</a></nav>
    <span class="push">{{ session?.displayName }}</span><button class="btn alt" (click)="logout()">Logout</button>
  </header>
  <main class="page"><div class="alert" *ngIf="message" [class.error]="error">{{ message }}</div>

    <ng-container *ngIf="path === '/staff-dashboard' || path === '/customer-dashboard'">
      <div class="toolbar"><div><div class="eyebrow">{{ session?.role === 'STAFF' ? 'Bank-wide overview' : 'Your account overview' }}</div><h1>{{ session?.role === 'STAFF' ? 'Staff Dashboard' : 'Welcome, ' + session?.displayName }}</h1></div></div>
      <div class="grid"><div class="card metric" *ngFor="let metric of metrics"><div class="muted">{{ metric.label }}</div><div class="number">{{ metric.value }}</div></div></div>
      <section class="card" *ngIf="session?.role === 'STAFF'" style="margin-top:20px"><h2>Recent Bank Transactions</h2><div class="table-wrap"><table><tr><th>Date</th><th>Customer ID</th><th>Customer</th><th>Card</th><th>Type</th><th>Merchant</th><th>Amount</th><th>Status</th><th>Reason</th></tr><tr *ngFor="let tx of dashboard?.recentTransactions"><td>{{ tx.transactionDate | date:'medium' }}</td><td>{{ tx.customerId }}</td><td>{{ tx.customerName }}</td><td>{{ tx.cardNumber }}</td><td>{{ tx.transactionType }}</td><td>{{ tx.merchant || '—' }}</td><td>₹{{ tx.amount }}</td><td><span class="tag" [class.blocked]="tx.status === 'FAILED'">{{ tx.status }}</span></td><td>{{ tx.failureReason || '—' }}</td></tr></table></div></section>
      <section class="card" *ngIf="session?.role === 'CUSTOMER' && featureScore" style="margin-top:20px"><h2>Credit Health</h2><div class="grid"><div><b>Score</b><div class="number">{{featureScore.score}} / 900</div></div><div><b>Rating</b><div>{{featureScore.rating}}</div></div><div><b>Reward points</b><div class="number">{{featureScore.rewardPoints}}</div></div><div><b>Cashback balance</b><div class="number">₹{{featureScore.cashbackBalance}}</div></div></div></section><div class="two" *ngIf="session?.role === 'CUSTOMER'"><section class="card"><h2>My cards</h2><div *ngFor="let card of dashboard?.cards" style="padding:9px 0;border-bottom:1px solid #eee"><b>{{ card.cardType }} · {{ card.cardNumber }}</b><div class="muted">Available: ₹{{ card.availableCredit }} · Due: ₹{{ card.outstandingAmount }}</div></div></section><section class="card"><h2>Recent activity</h2><div *ngFor="let tx of dashboard?.recentTransactions" style="padding:9px 0;border-bottom:1px solid #eee"><b>{{ tx.transactionType }}</b> · ₹{{ tx.amount }} · <span class="tag" [class.blocked]="tx.status === 'FAILED'">{{ tx.status }}</span></div></section></div>
    </ng-container>

    <ng-container *ngIf="path === '/customers'"><div class="toolbar"><h1>Customer Management</h1><button class="btn" (click)="showForm = 'customer'">Add customer</button></div><section class="card" *ngIf="showForm === 'customer'"><div class="form-grid"><div><label>Name</label><input [(ngModel)]="customer.name"></div><div><label>Email</label><input [(ngModel)]="customer.email" type="email"></div><div><label>Mobile number</label><input [(ngModel)]="customer.mobileNumber"></div><div><label>PAN number</label><input [(ngModel)]="customer.panNumber"></div></div><button class="btn" (click)="saveCustomer()">Save customer</button></section><section class="card"><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Mobile</th><th>PAN</th><th></th></tr><tr *ngFor="let c of list"><td>{{c.id}}</td><td>{{c.name}}</td><td>{{c.email}}</td><td>{{c.mobileNumber}}</td><td>{{c.panNumber}}</td><td><button class="btn alt" (click)="editCustomer(c)">Edit</button> <button class="btn warn" (click)="remove('/customers/' + c.id)">Delete</button></td></tr></table></div></section></ng-container>

    <ng-container *ngIf="path === '/cards' || path === '/my-cards'"><div class="toolbar"><h1>{{path === '/cards' ? 'Credit Card Management' : 'My Cards'}}</h1><button class="btn" *ngIf="path === '/cards'" (click)="showForm = 'card'">Issue card</button></div><section class="card" *ngIf="showForm === 'card'"><h2>Issue a card</h2><div class="form-grid"><div><label>Customer ID</label><input type="number" [(ngModel)]="card.customerId" (ngModelChange)="lookupCustomer()"></div><div><label>Customer Name</label><input [ngModel]="cardCustomerName" readonly placeholder="Automatically filled from customer ID"></div><div><label>Card type</label><select [(ngModel)]="card.cardType"><option>SILVER</option><option>GOLD</option><option>PLATINUM</option></select></div><div><label>Credit limit</label><input type="number" [(ngModel)]="card.creditLimit"></div><div><label>Expiry date</label><input type="date" [(ngModel)]="card.expiryDate"></div></div><button class="btn" (click)="saveCard()">Issue card</button></section><section class="card"><div class="table-wrap"><table><tr><th>Card</th><th>Customer ID</th><th>Customer</th><th>Limit</th><th>Available</th><th>Outstanding</th><th>Status</th><th></th></tr><tr *ngFor="let c of list"><td>{{c.cardType}}<br><b>{{c.cardNumber}}</b></td><td>{{c.customerId}}</td><td>{{c.customerName}}</td><td>₹{{c.creditLimit}}</td><td>₹{{c.availableCredit}}</td><td>₹{{c.outstandingAmount}}</td><td><span class="tag" [class.blocked]="c.status === 'BLOCKED'">{{c.status}}</span></td><td><button class="btn warn" *ngIf="path === '/my-cards' && c.status === 'ACTIVE'" (click)="block(c)">Block</button><button class="btn alt" *ngIf="path === '/cards'" (click)="toggleCard(c)">{{c.status === 'ACTIVE' ? 'Block' : 'Unblock'}}</button></td></tr></table></div></section></ng-container>

    <ng-container *ngIf="path === '/merchants'"><div class="toolbar"><h1>Merchant Management</h1><button class="btn" (click)="showForm = 'merchant'">Add merchant</button></div><section class="card" *ngIf="showForm === 'merchant'"><div class="form-grid"><div><label>Name</label><input [(ngModel)]="merchant.name"></div><div><label>Category</label><input [(ngModel)]="merchant.category"></div><div><label>Location</label><input [(ngModel)]="merchant.location"></div></div><button class="btn" (click)="saveMerchant()">Save merchant</button></section><section class="card"><table><tr><th>Name</th><th>Category</th><th>Location</th><th></th></tr><tr *ngFor="let m of list"><td>{{m.name}}</td><td>{{m.category}}</td><td>{{m.location}}</td><td><button class="btn warn" (click)="remove('/merchants/' + m.id)">Delete</button></td></tr></table></section></ng-container>

    <ng-container *ngIf="(path === '/purchase' || path === '/payment') && session?.role === 'CUSTOMER'"><h1>{{path === '/purchase' ? 'Make a Purchase' : 'Pay Credit Card Bill'}}</h1><section class="card" style="max-width:620px"><p class="muted" *ngIf="path === '/payment'">Only your own card can be selected and paid.</p><label>Card number</label><select [(ngModel)]="transaction.cardNumber"><option value="">Select your card</option><option *ngFor="let c of ownCardOptions" [value]="c.cardNumber">{{c.cardNumber}} — {{path === '/payment' ? 'Outstanding: ₹' + c.outstandingAmount : 'Available credit: ₹' + c.availableCredit}}</option></select><ng-container *ngIf="path === '/purchase'"><label>Merchant</label><select [(ngModel)]="transaction.merchantId"><option [ngValue]="null">Select merchant</option><option *ngFor="let m of merchantOptions" [ngValue]="m.id">{{m.name}} — {{m.category}}</option></select></ng-container><label>Amount (₹)</label><input type="number" min="0.01" [(ngModel)]="transaction.amount"><button class="btn" (click)="submitTransaction()">{{path === '/purchase' ? 'Confirm purchase' : 'Confirm bill payment'}}</button></section></ng-container>

    <ng-container *ngIf="path === '/transactions' || path === '/my-transactions'"><div class="toolbar"><h1>{{path === '/transactions' ? 'Transaction History' : 'My Transactions'}}</h1><button class="btn alt" (click)="loadTransactions()">Refresh</button></div><section class="card"><div class="table-wrap"><table><tr><th>Date</th><th *ngIf="session?.role === 'STAFF'">Customer ID</th><th *ngIf="session?.role === 'STAFF'">Customer</th><th>Card</th><th>Type</th><th>Merchant</th><th>Amount</th><th>Status</th><th>Reason</th></tr><tr *ngFor="let tx of list"><td>{{tx.transactionDate | date:'medium'}}</td><td *ngIf="session?.role === 'STAFF'">{{tx.customerId}}</td><td *ngIf="session?.role === 'STAFF'">{{tx.customerName}}</td><td>{{tx.cardNumber}}</td><td>{{tx.transactionType}}</td><td>{{tx.merchant || '—'}}</td><td>₹{{tx.amount}}</td><td><span class="tag" [class.blocked]="tx.status === 'FAILED'">{{tx.status}}</span></td><td>{{tx.failureReason || '—'}}</td></tr></table></div></section></ng-container>

    <ng-container *ngIf="path === '/statements'"><div class="toolbar"><h1>Monthly Statements</h1><button class="btn" (click)="showForm = 'statement'">Generate statement</button></div><section class="card" *ngIf="showForm === 'statement'"><label>My card</label><select [(ngModel)]="statement.cardId" (ngModelChange)="loadStatementTransactions()"><option *ngFor="let c of ownCardOptions" [ngValue]="c.id">{{c.cardNumber}}</option></select><label>Statement month</label><input type="month" [(ngModel)]="statement.month" (ngModelChange)="loadStatementTransactions()"><button class="btn" (click)="generateStatement()">Generate</button></section><section class="card"><table><tr><th>Period</th><th>Card</th><th>Opening</th><th>Purchases</th><th>Payments</th><th>Closing</th></tr><tr *ngFor="let s of list"><td>{{s.periodStart | date}} – {{s.periodEnd | date}}</td><td>{{s.cardNumber}}</td><td>₹{{s.openingBalance}}</td><td>₹{{s.purchases}}</td><td>₹{{s.payments}}</td><td>₹{{s.closingBalance}}</td></tr></table></section><section class="card" style="margin-top:20px"><h2>Purchase and Payment Activity</h2><div class="table-wrap"><table><tr><th>Date</th><th>Type</th><th>Card</th><th>Merchant</th><th>Amount</th><th>Status</th><th>Reason</th></tr><tr *ngFor="let tx of statementTransactions"><td>{{tx.transactionDate | date:'medium'}}</td><td>{{tx.transactionType}}</td><td>{{tx.cardNumber}}</td><td>{{tx.merchant || '—'}}</td><td>₹{{tx.amount}}</td><td><span class="tag" [class.blocked]="tx.status === 'FAILED'">{{tx.status}}</span></td><td>{{tx.failureReason || '—'}}</td></tr><tr *ngIf="statementTransactions.length === 0"><td colspan="7" class="muted">No purchases or payments for the selected statement period.</td></tr></table></div></section></ng-container>
  </main>
</div>`
})
export class PortalPageComponent implements OnInit {
  api = inject(Api); router = inject(Router);
  path = '/'; session: Session | null = null; message = ''; error = false; showForm = '';
  list: any[] = []; dashboard: any; featureScore: any; metrics: {label: string; value: unknown}[] = [];
  username = ''; password = ''; registration = {name: '', email: '', username: '', password: ''}; customer: any = {}; merchant: any = {};
  card: any = {cardType: 'GOLD', creditLimit: 50000, expiryDate: ''}; cardCustomerName = '';
  transaction: any = {cardNumber: '', merchantId: null, amount: null}; statement: any = {cardId: null, month: new Date().toISOString().slice(0, 7)};
  merchantOptions: any[] = []; ownCardOptions: any[] = []; statementTransactions: any[] = [];

  get isPortal() { return !!this.session && this.path !== '/' && !this.path.includes('login'); }
  ngOnInit() { this.router.events.pipe(filter(event => event instanceof NavigationEnd)).subscribe(() => this.activate()); this.activate(); }
  activate() { this.path = this.router.url.split('?')[0] || '/'; this.session = this.api.session(); this.message = ''; this.showForm = ''; if (this.path !== '/' && !this.path.includes('login') && this.path !== '/customer-signup' && !this.session) { this.router.navigateByUrl('/'); return; } if (this.path.includes('staff') && this.session?.role === 'CUSTOMER') { this.router.navigateByUrl('/customer-dashboard'); return; } this.load(); }
  login() { this.api.login(this.username, this.password).subscribe({ next: session => { const required = this.path === '/staff-login' ? 'STAFF' : 'CUSTOMER'; if (session.role !== required) { this.notice('Please use the correct portal for this account.', true); return; } localStorage.setItem('cc_auth', btoa(this.username + ':' + this.password)); localStorage.setItem('cc_session', JSON.stringify(session)); this.router.navigateByUrl(session.role === 'STAFF' ? '/staff-dashboard' : '/customer-dashboard'); }, error: (e: any) => this.notice(e.error?.message || 'Invalid username or password.', true) }); }
  signup() { this.api.signup(this.registration).subscribe({next: () => { this.notice('Account created. Please sign in with your new username or email.'); this.registration = {name: '', email: '', username: '', password: ''}; this.router.navigateByUrl('/customer-login'); }, error: (e: any) => this.notice(e.error?.message || 'Unable to create your account.', true)}); }
  logout() { this.api.logout(); this.router.navigateByUrl('/'); }
  load() { if (!this.session) return; if (this.path.includes('dashboard')) { this.api.get<any>(this.session.role === 'STAFF' ? '/staff/dashboard' : '/dashboard').subscribe({ next: d => { this.dashboard = d; if(this.session?.role === 'CUSTOMER') this.api.get<any>('/features/score').subscribe(v => this.featureScore = v); const staff = this.session?.role === 'STAFF'; const raw = staff ? [['Total customers', d.totalCustomers], ['Total credit cards', d.totalCards], ['Total merchants', d.totalMerchants], ['Total transactions', d.totalTransactions], ['Active cards', d.activeCards], ['Blocked cards', d.blockedCards], ['Total outstanding', '₹' + d.totalOutstandingAmount], ['Total available credit', '₹' + d.totalAvailableCredit]] : [['Cards', d.totalCards], ['Outstanding', '₹' + d.totalOutstandingAmount], ['Available credit', '₹' + d.totalAvailableCredit]]; this.metrics = raw.map(item => ({label: String(item[0]), value: item[1]})); }, error: () => this.notice('Could not load dashboard.', true) }); return; } if (this.path === '/customers') this.fetch('/customers'); else if (this.path === '/cards') this.fetch('/cards'); else if (this.path === '/my-cards') this.loadOwnCards(); else if (this.path === '/merchants') this.fetch('/merchants'); else if (this.path === '/purchase' || this.path === '/payment') { this.loadOwnCards(); if (this.path === '/purchase') this.api.get<any[]>('/purchase-merchants').subscribe({next: items => this.merchantOptions = items, error: () => this.notice('No merchants are available for purchases yet.', true)}); } else if (this.path === '/transactions' || this.path === '/my-transactions') this.loadTransactions(); else if (this.path === '/statements') { this.fetch('/statements/mine'); this.loadOwnCards(); this.loadStatementTransactions(); } }
  fetch(path: string) { this.api.get<any[]>(path).subscribe({next: items => this.list = items, error: (e: any) => this.notice(e.error?.message || 'Unable to load data.', true)}); }
  loadOwnCards() { this.api.get<any[]>('/cards/mine').subscribe({next: cards => { this.ownCardOptions = cards; if (this.path === '/my-cards') this.list = cards; }, error: (e: any) => this.notice(e.error?.message || 'Unable to load cards.', true)}); }
  loadStatementTransactions() { const month = this.statement.month; if (!month) return; const start = month + '-01'; const date = new Date(start + 'T00:00:00'); const end = new Date(date.getFullYear(), date.getMonth() + 1, 0).toISOString().slice(0, 10); const cardFilter = this.statement.cardId ? '&cardId=' + this.statement.cardId : ''; this.api.get<any[]>('/transactions?from=' + start + '&to=' + end + cardFilter).subscribe({next: transactions => this.statementTransactions = transactions, error: () => this.statementTransactions = []}); }
  notice(message: string, error = false) { this.message = message; this.error = error; }
  lookupCustomer() { this.cardCustomerName = ''; if (!this.card.customerId) return; this.api.get<any>('/customers/' + this.card.customerId).subscribe({next: customer => this.cardCustomerName = customer.name, error: () => this.cardCustomerName = 'Customer not found'}); }
  saveCustomer() { const request = this.customer.id ? this.api.put<any>('/customers/' + this.customer.id, this.customer) : this.api.post<any>('/customers', this.customer); request.subscribe({next: () => { this.notice('Customer saved.'); this.customer = {}; this.showForm = ''; this.fetch('/customers'); }, error: (e: any) => this.notice(e.error?.message || 'Please check the customer details.', true)}); }
  editCustomer(customer: any) { this.customer = {...customer}; this.showForm = 'customer'; }
  saveCard() { this.api.post<any>('/cards', {...this.card, customerId: +this.card.customerId, creditLimit: +this.card.creditLimit}).subscribe({next: () => { this.notice('Card issued successfully.'); this.showForm = ''; this.fetch('/cards'); }, error: (e: any) => this.notice(e.error?.message || 'Please check the card details.', true)}); }
  saveMerchant() { this.api.post<any>('/merchants', this.merchant).subscribe({next: () => { this.notice('Merchant saved.'); this.merchant = {}; this.showForm = ''; this.fetch('/merchants'); }, error: (e: any) => this.notice(e.error?.message || 'Please check the merchant details.', true)}); }
  remove(path: string) { if (confirm('Delete this record?')) this.api.delete(path).subscribe({next: () => { this.notice('Record deleted.'); this.load(); }, error: (e: any) => this.notice(e.error?.message || 'Cannot delete this record.', true)}); }
  toggleCard(card: any) { this.api.patch<any>('/cards/' + card.id + '/status?value=' + (card.status === 'ACTIVE' ? 'BLOCKED' : 'ACTIVE')).subscribe({next: () => { this.notice('Card status updated.'); this.fetch('/cards'); }, error: (e: any) => this.notice(e.error?.message || 'Update failed.', true)}); }
  block(card: any) { this.api.patch<any>('/cards/' + card.id + '/block').subscribe({next: () => { this.notice('Your card has been blocked.'); this.loadOwnCards(); }, error: (e: any) => this.notice(e.error?.message || 'Unable to block card.', true)}); }
  submitTransaction() { const endpoint = this.path === '/purchase' ? '/transactions/purchase' : '/payments'; this.api.post<any>(endpoint, {...this.transaction, amount: +this.transaction.amount}).subscribe({next: tx => { this.notice(tx.status === 'SUCCESS' ? 'Transaction completed successfully.' : 'Transaction failed: ' + tx.failureReason, tx.status !== 'SUCCESS'); this.transaction = {cardNumber: '', merchantId: null, amount: null}; this.loadOwnCards(); }, error: (e: any) => this.notice(e.error?.message || 'Transaction could not be processed.', true)}); }
  loadTransactions() { this.fetch('/transactions'); }
  generateStatement() { this.api.post<any>('/statements/card/' + this.statement.cardId + '?month=' + this.statement.month).subscribe({next: () => { this.notice('Statement generated.'); this.showForm = ''; this.fetch('/statements/mine'); this.loadStatementTransactions(); }, error: (e: any) => this.notice(e.error?.message || 'Unable to generate statement.', true)}); }
}

export const routes: Routes = [{ path: '**', component: PortalPageComponent }];