import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NavigationEnd, Router, RouterLink, RouterLinkActive, RouterOutlet, Routes } from '@angular/router';
import { filter } from 'rxjs';
import { Api, Session } from './api.service';

@Component({ selector: 'app-root', standalone: true, imports: [RouterOutlet], template: '<router-outlet />' })
export class AppComponent {}

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, RouterLinkActive],
  template: `
<section class="public-shell" *ngIf="isPublicPage">
  <header class="public-nav">
    <a class="public-brand" routerLink="/" aria-label="Mosaic Vault home">
      <svg class="mosaic-mark" viewBox="0 0 48 48" aria-hidden="true"><rect x="4" y="4" width="18" height="18" rx="5"></rect><rect x="26" y="4" width="18" height="18" rx="5"></rect><rect x="4" y="26" width="18" height="18" rx="5"></rect><path d="M26 26h7a4 4 0 1 1 7 0h4v18H26z"></path></svg>
      <span>Mosaic <em>Vault</em></span>
    </a>
    <nav class="public-links" aria-label="Public navigation"><a href="#home">Home</a><a href="#about">About Us</a><a href="#faqs">FAQs</a><a href="#contact">Contact Us</a></nav>
  </header>

  <div class="mosaic-loader" *ngIf="path === '/'" aria-hidden="true"><div class="loader-puzzle"><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span><span class="load-piece"></span></div><span class="loader-name">Mosaic Vault</span></div>
  <main id="home" class="landing" *ngIf="path === '/'">
    <section class="landing-copy">
      <p class="landing-kicker">A clearer way to manage credit</p>
      <h1><span>Your card,</span><span>Your control,</span><span>Your vault.</span></h1>
      <p class="landing-tagline">Every piece of your credit life in one picture.</p>
      <p class="landing-description">Mosaic Vault brings cards, purchases, bill payments, statements, rewards, and credit health together in one secure, simple place.</p>
      <div class="landing-actions"><a class="public-button primary" routerLink="/account-request">Apply</a><a class="public-button secondary" routerLink="/customer-login">Login as Customer</a><a class="public-button text" routerLink="/staff-login">Login as Admin <span aria-hidden="true">→</span></a></div>
    </section>
    <section class="vault-illustration" aria-label="Mosaic Vault credit-card management illustration">
      <div class="illustration-glow"></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div>
      <div class="statement-card"><span class="statement-label">MONTHLY SNAPSHOT</span><strong>Everything aligned.</strong><div class="statement-bars"><i></i><i></i><i></i></div><small>Cards · payments · rewards</small></div>
      <div class="vault-card"><div class="vault-card-top"><span>MOSAIC VAULT</span><span>◈</span></div><div class="vault-chip"></div><div class="vault-card-number">•••• 4831</div><div class="vault-card-footer"><span>YOUR CARD</span><b>MV</b></div></div>
      <div class="puzzle-board"><span class="piece piece-a"></span><span class="piece piece-b"></span><span class="piece piece-c"></span><span class="piece piece-d"></span><span class="piece piece-e"></span><span class="piece piece-f"></span></div>
      <div class="insight-card"><span class="insight-dot"></span><div><small>CREDIT HEALTH</small><strong>In view</strong></div></div>
    </section>
  </main>

  <main id="about" class="public-page" *ngIf="path === '/'">
    <p class="landing-kicker">About Mosaic Vault</p><h1>Credit management, arranged around people.</h1><p class="public-lead">Mosaic Vault is a role-based Credit Card Management System designed to make the complete card journey visible, secure, and easy to manage.</p>
    <section class="about-grid"><article><span class="feature-number">01</span><h2>For customers</h2><p>Customers can request an account and card, create online credentials, make purchases, pay bills, review statements, download PDF records, and track their credit health.</p></article><article><span class="feature-number">02</span><h2>For bank staff</h2><p>Staff can review account and card requests, maintain customer, merchant, and card records, issue approved cards, and monitor bank-wide activity.</p></article><article><span class="feature-number">03</span><h2>For clarity</h2><p>Every workflow is linked: requests lead to approvals, cards lead to transactions, and transactions lead to statements, rewards, and credit-health insights.</p></article></section>
    <section class="public-callout"><div><p class="landing-kicker">One secure system</p><h2>Built for a complete credit-card lifecycle.</h2></div><p>From onboarding to payment history, Mosaic Vault keeps the right information with the right role—without making the experience complicated.</p></section>
  </main>

  <main id="faqs" class="public-page" *ngIf="path === '/'">
    <p class="landing-kicker">Frequently asked questions</p><h1>Helpful answers, in one place.</h1><p class="public-lead">Here are common questions about using Mosaic Vault.</p>
    <section class="faq-list"><details open><summary>1. What is Mosaic Vault?</summary><p>Mosaic Vault is a role-based credit-card management system for customers and bank staff.</p></details><details><summary>2. How do I create a customer account?</summary><p>Select Apply, submit your basic details, wait for bank staff approval, then create a username and password using your approved email address.</p></details><details><summary>3. Can I sign in with my email address?</summary><p>Yes. Customers can sign in using either their username or their registered email address together with their password.</p></details><details><summary>4. How can I request a credit card?</summary><p>After signing in as a customer, open Request Card, choose a card type, and submit the request. Staff will review it before issuing the card.</p></details><details><summary>5. Why is my card request still visible after approval?</summary><p>An approved request remains visible to staff as a reminder until the card is actually issued to the customer.</p></details><details><summary>6. Can I make a purchase from any merchant?</summary><p>You can choose from the active merchant catalog maintained by bank staff and pay only with your own active credit card.</p></details><details><summary>7. Where can I see my outstanding amount?</summary><p>Your outstanding amount is shown on your dashboard, card details, and when you select a card on the Pay Bill page.</p></details><details><summary>8. How are reward points and cashback calculated?</summary><p>Successful purchases earn reward points, while successful bill payments add cashback according to the portal rules.</p></details><details><summary>9. Can I download my monthly statement?</summary><p>Yes. Generate a statement from the Statements page, then select Download PDF to save a copy to your device.</p></details><details><summary>10. What should I do if I cannot access my account?</summary><p>Use the contact details below to reach the Mosaic Vault support team. They can help you understand the next appropriate step.</p></details></section>
  </main>

  <main id="contact" class="public-page contact-page" *ngIf="path === '/'">
    <p class="landing-kicker">Contact Mosaic Vault</p><h1>We are here when you need clarity.</h1><p class="public-lead">For account, card, payment, or access-related questions, contact the Mosaic Vault support desk.</p>
    <section class="contact-grid"><a class="contact-card" href="mailto:support&#64;mosaicvault.in"><span>Email us</span><strong>support&#64;mosaicvault.in</strong><small>For general support and account queries</small></a><a class="contact-card" href="tel:+911800202600"><span>Customer helpline</span><strong>1800 202 600</strong><small>Available for customer assistance</small></a><a class="contact-card" href="tel:+919876543210"><span>Priority support</span><strong>+91 98765 43210</strong><small>For urgent card and payment help</small></a></section>
    <section class="public-callout"><div><p class="landing-kicker">Support note</p><h2>Please keep your account details private.</h2></div><p>Mosaic Vault support will never ask you to share your password. For your protection, do not send passwords through email or phone calls.</p></section>
  </main>
</section>
<section class="page auth-page" *ngIf="path === '/staff-login' || path === '/customer-login'"><div class="card login"><div class="eyebrow">{{ path === '/staff-login' ? 'Mosaic Vault staff' : 'Mosaic Vault customer' }} access</div><h2>Welcome back</h2><div class="alert error" *ngIf="message">{{ message }}</div><label>{{ path === '/staff-login' ? 'Username' : 'Username or email' }}</label><input [(ngModel)]="username" autocomplete="username"><label>Password</label><input type="password" [(ngModel)]="password" autocomplete="current-password" (keyup.enter)="login()"><p class="login-help" *ngIf="path === '/customer-login'">New customer? <a routerLink="/customer-signup">Create an account</a></p><button class="btn" style="width:100%;margin-top:20px" (click)="login()">Sign in</button><p class="muted" *ngIf="path === '/staff-login'">Demo staff access: staff / Staff&#64;123</p><a routerLink="/">Back to welcome</a></div></section>

<section class="page" *ngIf="path === '/customer-signup'"><div class="card login"><div class="eyebrow">Mosaic Vault customer registration</div><h2>Create your online account</h2><p class="muted">Your name and email must match the customer profile created by bank staff.</p><div class="alert" *ngIf="message" [class.error]="error">{{ message }}</div><label>Full name</label><input [(ngModel)]="registration.name" autocomplete="name"><label>Email address</label><input type="email" [(ngModel)]="registration.email" autocomplete="email"><label>Choose username</label><input [(ngModel)]="registration.username" autocomplete="username"><label>Choose password</label><input type="password" [(ngModel)]="registration.password" autocomplete="new-password"><button class="btn" style="width:100%;margin-top:20px" (click)="signup()">Create account</button><p class="muted">Already registered? <a routerLink="/customer-login">Sign in</a></p><a routerLink="/">Back to welcome</a></div></section>

<section class="page" *ngIf="path === '/account-request'"><div class="card login"><div class="eyebrow">Mosaic Vault account request</div><h2>Request a customer account</h2><p class="muted">Bank staff will review your details. After approval, return to create your username and password.</p><div class="alert" *ngIf="message" [class.error]="error">{{message}}</div><label>Full name</label><input [(ngModel)]="onboarding.name"><label>Email</label><input type="email" [(ngModel)]="onboarding.email"><label>Mobile number</label><input [(ngModel)]="onboarding.mobileNumber"><label>PAN number</label><input [(ngModel)]="onboarding.panNumber"><button class="btn" style="width:100%;margin-top:20px" (click)="submitOnboarding()">Submit request</button><p class="muted"><a routerLink="/customer-login">Already approved? Create/sign in</a></p></div></section><div class="shell" *ngIf="isPortal">
  <header class="top"><a class="brand" routerLink="/">Mosaic Vault</a>
    <nav class="nav" *ngIf="session?.role === 'STAFF'"><a routerLink="/staff-dashboard" routerLinkActive="active">Dashboard</a><a routerLink="/customers" routerLinkActive="active">Customers</a><a routerLink="/account-requests" routerLinkActive="active">Account Requests</a><a routerLink="/cards" routerLinkActive="active">Credit Cards</a><a routerLink="/card-requests" routerLinkActive="active">Card Requests</a><a routerLink="/merchants" routerLinkActive="active">Merchants</a><a routerLink="/transactions" routerLinkActive="active">Transactions</a></nav>
    <nav class="nav" *ngIf="session?.role === 'CUSTOMER'"><a routerLink="/customer-dashboard" routerLinkActive="active">Dashboard</a><a routerLink="/my-cards" routerLinkActive="active">My Cards</a><a routerLink="/card-request" routerLinkActive="active">Request Card</a><a routerLink="/purchase" routerLinkActive="active">Make Purchase</a><a routerLink="/payment" routerLinkActive="active">Pay Bill</a><a routerLink="/my-transactions" routerLinkActive="active">My Transactions</a><a routerLink="/statements" routerLinkActive="active">Statements</a></nav>
    <span class="push">{{ session?.displayName }}</span><button class="btn alt" (click)="logout()">Logout</button>
  </header>
  <main class="page"><div class="alert" *ngIf="message" [class.error]="error">{{ message }}</div>

    <ng-container *ngIf="path === '/staff-dashboard' || path === '/customer-dashboard'">
      <div class="toolbar"><div><div class="eyebrow">{{ session?.role === 'STAFF' ? 'Bank-wide overview' : 'Your account overview' }}</div><h1>{{ session?.role === 'STAFF' ? 'Staff Dashboard' : 'Welcome, ' + session?.displayName }}</h1></div></div>
      <div class="grid"><div class="card metric" *ngFor="let metric of metrics"><div class="muted">{{ metric.label }}</div><div class="number">{{ metric.value }}</div></div></div>
      <section class="card" *ngIf="session?.role === 'STAFF'" style="margin-top:20px"><h2>Recent Bank Transactions</h2><div class="table-wrap"><table><tr><th>Date</th><th>Customer ID</th><th>Customer</th><th>Card</th><th>Type</th><th>Merchant</th><th>Amount</th><th>Status</th><th>Reason</th></tr><tr *ngFor="let tx of dashboard?.recentTransactions"><td>{{ tx.transactionDate | date:'medium' }}</td><td>{{ tx.customerId }}</td><td>{{ tx.customerName }}</td><td>{{ tx.cardNumber }}</td><td>{{ tx.transactionType }}</td><td>{{ tx.merchant || '—' }}</td><td>₹{{ tx.amount }}</td><td><span class="tag" [class.blocked]="tx.status === 'FAILED'">{{ tx.status }}</span></td><td>{{ tx.failureReason || '—' }}</td></tr></table></div></section>
      <section class="card" *ngIf="session?.role === 'CUSTOMER' && featureScore" style="margin-top:20px"><h2>Credit Health</h2><div class="grid"><div><b>Score</b><div class="number">{{featureScore.score}} / 900</div></div><div><b>Rating</b><div>{{featureScore.rating}}</div></div><div><b>Reward points</b><div class="number">{{featureScore.rewardPoints}}</div></div><div><b>Cashback balance</b><div class="number">₹{{featureScore.cashbackBalance}}</div></div></div></section><div class="two" *ngIf="session?.role === 'CUSTOMER'"><section class="card"><h2>My cards</h2><div *ngFor="let card of dashboard?.cards" style="padding:9px 0;border-bottom:1px solid #eee"><b>{{ card.cardType }} · {{ card.cardNumber }}</b><div class="muted">Available: ₹{{ card.availableCredit }} · Due: ₹{{ card.outstandingAmount }}</div></div></section><section class="card"><h2>Recent activity</h2><div *ngFor="let tx of dashboard?.recentTransactions" style="padding:9px 0;border-bottom:1px solid #eee"><b>{{ tx.transactionType }}</b> · ₹{{ tx.amount }} · <span class="tag" [class.blocked]="tx.status === 'FAILED'">{{ tx.status }}</span></div></section></div>
    </ng-container>

    <ng-container *ngIf="path === '/account-requests'"><div class="toolbar"><h1>Customer Account Requests</h1><button class="btn alt" (click)="loadRequests()">Refresh</button></div><section class="card"><div class="table-wrap"><table><tr><th>Name</th><th>Email</th><th>Mobile</th><th>PAN</th><th>Action</th></tr><tr *ngFor="let r of list"><td>{{r.name}}</td><td>{{r.email}}</td><td>{{r.mobileNumber}}</td><td>{{r.panNumber}}</td><td><button class="btn" (click)="reviewOnboarding(r,'APPROVED')">Approve</button> <button class="btn warn" (click)="reviewOnboarding(r,'REJECTED')">Reject</button></td></tr></table></div></section></ng-container>    <ng-container *ngIf="path === '/customers'"><div class="toolbar"><h1>Customer Management</h1><button class="btn" (click)="showForm = 'customer'">Add customer</button></div><section class="card" *ngIf="showForm === 'customer'"><div class="form-grid"><div><label>Name</label><input [(ngModel)]="customer.name"></div><div><label>Email</label><input [(ngModel)]="customer.email" type="email"></div><div><label>Mobile number</label><input [(ngModel)]="customer.mobileNumber"></div><div><label>PAN number</label><input [(ngModel)]="customer.panNumber"></div></div><button class="btn" (click)="saveCustomer()">Save customer</button></section><section class="card"><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Mobile</th><th>PAN</th><th></th></tr><tr *ngFor="let c of list"><td>{{c.id}}</td><td>{{c.name}}</td><td>{{c.email}}</td><td>{{c.mobileNumber}}</td><td>{{c.panNumber}}</td><td><button class="btn alt" (click)="editCustomer(c)">Edit</button> <button class="btn warn" (click)="remove('/customers/' + c.id)">Delete</button></td></tr></table></div></section></ng-container>

    <ng-container *ngIf="path === '/cards' || path === '/my-cards'"><div class="toolbar"><h1>{{path === '/cards' ? 'Credit Card Management' : 'My Cards'}}</h1><button class="btn" *ngIf="path === '/cards'" (click)="showForm = 'card'">Issue card</button></div><section class="card" *ngIf="showForm === 'card'"><h2>Issue a card</h2><div class="form-grid"><div><label>Customer ID</label><input type="number" [(ngModel)]="card.customerId" (ngModelChange)="lookupCustomer()"></div><div><label>Customer Name</label><input [ngModel]="cardCustomerName" readonly placeholder="Automatically filled from customer ID"></div><div><label>Card type</label><select [(ngModel)]="card.cardType"><option>SILVER</option><option>GOLD</option><option>PLATINUM</option></select></div><div><label>Credit limit</label><input type="number" [(ngModel)]="card.creditLimit"></div><div><label>Expiry date</label><input type="date" [(ngModel)]="card.expiryDate"></div></div><button class="btn" (click)="saveCard()">Issue card</button></section><section class="card"><div class="table-wrap"><table><tr><th>Card</th><th>Customer ID</th><th>Customer</th><th>Limit</th><th>Available</th><th>Outstanding</th><th>Status</th><th></th></tr><tr *ngFor="let c of list"><td>{{c.cardType}}<br><b>{{c.cardNumber}}</b></td><td>{{c.customerId}}</td><td>{{c.customerName}}</td><td>₹{{c.creditLimit}}</td><td>₹{{c.availableCredit}}</td><td>₹{{c.outstandingAmount}}</td><td><span class="tag" [class.blocked]="c.status === 'BLOCKED'">{{c.status}}</span></td><td><button class="btn warn" *ngIf="path === '/my-cards' && c.status === 'ACTIVE'" (click)="block(c)">Block</button><button class="btn alt" *ngIf="path === '/cards'" (click)="toggleCard(c)">{{c.status === 'ACTIVE' ? 'Block' : 'Unblock'}}</button></td></tr></table></div></section></ng-container>

    <ng-container *ngIf="path === '/card-request'"><h1>Request a Credit Card</h1><section class="card" style="max-width:620px"><label>Card type</label><select [(ngModel)]="cardApplication.cardType"><option>SILVER</option><option>GOLD</option><option>PLATINUM</option></select><button class="btn" (click)="submitCardApplication()">Submit card request</button><h2>My requests</h2><div *ngFor="let r of cardRequests">{{r.cardType}} — <span class="tag">{{r.status}}</span></div></section></ng-container><ng-container *ngIf="path === '/card-requests'"><h1>Customer Card Requests</h1><section class="card"><table><tr><th>Customer</th><th>Type</th><th>Action</th></tr><tr *ngFor="let r of cardRequests"><td>{{r.customerName}}</td><td>{{r.cardType}}</td><td><span class="tag" *ngIf="r.status === 'APPROVED'">Reminder: card still needs issuing</span><button class="btn" *ngIf="r.status === 'PENDING'" (click)="approveCardApplication(r)">Approve & Issue</button> <button class="btn warn" *ngIf="r.status === 'PENDING'" (click)="reviewCardApplication(r,'REJECTED')">Reject</button><button class="btn" *ngIf="r.status === 'APPROVED'" (click)="router.navigateByUrl('/cards?customerId=' + r.customerId + '&cardType=' + r.cardType)">Continue issuing card</button></td></tr></table></section></ng-container><ng-container *ngIf="path === '/merchants'"><div class="toolbar"><h1>Merchant Management</h1><button class="btn" (click)="showForm = 'merchant'">Add merchant</button></div><section class="card" *ngIf="showForm === 'merchant'"><div class="form-grid"><div><label>Name</label><input [(ngModel)]="merchant.name"></div><div><label>Category</label><input [(ngModel)]="merchant.category"></div><div><label>Location</label><input [(ngModel)]="merchant.location"></div></div><button class="btn" (click)="saveMerchant()">Save merchant</button></section><section class="card"><table><tr><th>Name</th><th>Category</th><th>Location</th><th></th></tr><tr *ngFor="let m of list"><td>{{m.name}}</td><td>{{m.category}}</td><td>{{m.location}}</td><td><button class="btn warn" (click)="remove('/merchants/' + m.id)">Delete</button></td></tr></table></section></ng-container>

    <ng-container *ngIf="(path === '/purchase' || path === '/payment') && session?.role === 'CUSTOMER'"><h1>{{path === '/purchase' ? 'Make a Purchase' : 'Pay Credit Card Bill'}}</h1><section class="card" style="max-width:620px"><p class="muted" *ngIf="path === '/payment'">Only your own card can be selected and paid.</p><label>Card number</label><select [(ngModel)]="transaction.cardNumber"><option value="">Select your card</option><option *ngFor="let c of ownCardOptions" [value]="c.cardNumber">{{c.cardNumber}} — {{path === '/payment' ? 'Outstanding: ₹' + c.outstandingAmount : 'Available credit: ₹' + c.availableCredit}}</option></select><ng-container *ngIf="path === '/purchase'"><label>Merchant</label><select [(ngModel)]="transaction.merchantId"><option [ngValue]="null">Select merchant</option><option *ngFor="let m of merchantOptions" [ngValue]="m.id">{{m.name}} — {{m.category}}</option></select></ng-container><label>Amount (₹)</label><input type="number" min="0.01" [(ngModel)]="transaction.amount"><button class="btn" (click)="submitTransaction()">{{path === '/purchase' ? 'Confirm purchase' : 'Confirm bill payment'}}</button></section></ng-container>

    <ng-container *ngIf="path === '/transactions' || path === '/my-transactions'"><div class="toolbar"><h1>{{path === '/transactions' ? 'Transaction History' : 'My Transactions'}}</h1><button class="btn alt" (click)="loadTransactions()">Refresh</button></div><section class="card"><div class="table-wrap"><table><tr><th>Date</th><th *ngIf="session?.role === 'STAFF'">Customer ID</th><th *ngIf="session?.role === 'STAFF'">Customer</th><th>Card</th><th>Type</th><th>Merchant</th><th>Amount</th><th>Status</th><th>Reason</th></tr><tr *ngFor="let tx of list"><td>{{tx.transactionDate | date:'medium'}}</td><td *ngIf="session?.role === 'STAFF'">{{tx.customerId}}</td><td *ngIf="session?.role === 'STAFF'">{{tx.customerName}}</td><td>{{tx.cardNumber}}</td><td>{{tx.transactionType}}</td><td>{{tx.merchant || '—'}}</td><td>₹{{tx.amount}}</td><td><span class="tag" [class.blocked]="tx.status === 'FAILED'">{{tx.status}}</span></td><td>{{tx.failureReason || '—'}}</td></tr></table></div></section></ng-container>

    <ng-container *ngIf="path === '/statements'"><div class="toolbar"><h1>Monthly Statements</h1><button class="btn" (click)="showForm = 'statement'">Generate statement</button></div><section class="card" *ngIf="showForm === 'statement'"><label>My card</label><select [(ngModel)]="statement.cardId" (ngModelChange)="loadStatementTransactions()"><option *ngFor="let c of ownCardOptions" [ngValue]="c.id">{{c.cardNumber}}</option></select><label>Statement month</label><input type="month" [(ngModel)]="statement.month" (ngModelChange)="loadStatementTransactions()"><button class="btn" (click)="generateStatement()">Generate</button></section><section class="card"><table><tr><th>Period</th><th>Card</th><th>Opening</th><th>Purchases</th><th>Payments</th><th>Closing</th><th>Download</th></tr><tr *ngFor="let s of list"><td>{{s.periodStart | date}} – {{s.periodEnd | date}}</td><td>{{s.cardNumber}}</td><td>₹{{s.openingBalance}}</td><td>₹{{s.purchases}}</td><td>₹{{s.payments}}</td><td>₹{{s.closingBalance}}</td><td><button class="btn alt" (click)="downloadStatement(s)">Download PDF</button></td></tr></table></section><section class="card" style="margin-top:20px"><h2>Purchase and Payment Activity</h2><div class="table-wrap"><table><tr><th>Date</th><th>Type</th><th>Card</th><th>Merchant</th><th>Amount</th><th>Status</th><th>Reason</th></tr><tr *ngFor="let tx of statementTransactions"><td>{{tx.transactionDate | date:'medium'}}</td><td>{{tx.transactionType}}</td><td>{{tx.cardNumber}}</td><td>{{tx.merchant || '—'}}</td><td>₹{{tx.amount}}</td><td><span class="tag" [class.blocked]="tx.status === 'FAILED'">{{tx.status}}</span></td><td>{{tx.failureReason || '—'}}</td></tr><tr *ngIf="statementTransactions.length === 0"><td colspan="7" class="muted">No purchases or payments for the selected statement period.</td></tr></table></div></section></ng-container>
  </main>
</div>`
})
export class PortalPageComponent implements OnInit {
  api = inject(Api); router = inject(Router);
  path = '/'; session: Session | null = null; message = ''; error = false; showForm = '';
  list: any[] = []; dashboard: any; featureScore: any; metrics: {label: string; value: unknown}[] = [];
  username = ''; password = ''; registration = {name: '', email: '', username: '', password: ''}; onboarding = {name: '', email: '', mobileNumber: '', panNumber: ''}; customer: any = {}; merchant: any = {};
  card: any = {cardType: 'GOLD', creditLimit: 50000, expiryDate: ''}; cardCustomerName = ''; cardApplication:any={cardType:'GOLD'}; cardRequests:any[]=[];
  transaction: any = {cardNumber: '', merchantId: null, amount: null}; statement: any = {cardId: null, month: new Date().toISOString().slice(0, 7)};
  merchantOptions: any[] = []; ownCardOptions: any[] = []; statementTransactions: any[] = [];

  get isPublicPage() { return ['/', '/about', '/faqs', '/contact'].includes(this.path); }
  get isPortal() { return !!this.session && !['/', '/about', '/faqs', '/contact', '/staff-login', '/customer-login', '/customer-signup', '/account-request'].includes(this.path); }
  ngOnInit() { this.router.events.pipe(filter(event => event instanceof NavigationEnd)).subscribe(() => this.activate()); this.activate(); }
  activate() { this.path = this.router.url.split('?')[0].split('#')[0] || '/'; if(['/about','/faqs','/contact'].includes(this.path)){const section=this.path.slice(1);this.router.navigate(['/'],{fragment:section}).then(()=>setTimeout(()=>document.getElementById(section)?.scrollIntoView({behavior:'smooth'})));return;} this.session = this.api.session(); this.message = ''; this.showForm = ''; if(this.path === '/cards'){const q=this.router.parseUrl(this.router.url).queryParams;if(q['customerId']){this.card.customerId=+q['customerId'];this.card.cardType=q['cardType']||'GOLD';this.showForm='card';this.lookupCustomer();}} if (!['/', '/about', '/faqs', '/contact', '/staff-login', '/customer-login', '/customer-signup', '/account-request'].includes(this.path) && !this.session) { this.router.navigateByUrl('/'); return; } if (this.path.includes('staff') && this.session?.role === 'CUSTOMER') { this.router.navigateByUrl('/customer-dashboard'); return; } this.load(); }
  login() { this.api.login(this.username, this.password).subscribe({ next: session => { const required = this.path === '/staff-login' ? 'STAFF' : 'CUSTOMER'; if (session.role !== required) { this.notice('Please use the correct portal for this account.', true); return; } localStorage.setItem('cc_auth', btoa(this.username + ':' + this.password)); localStorage.setItem('cc_session', JSON.stringify(session)); this.router.navigateByUrl(session.role === 'STAFF' ? '/staff-dashboard' : '/customer-dashboard'); }, error: (e: any) => this.notice(e.error?.message || 'Invalid username or password.', true) }); }
  signup() { this.api.signup(this.registration).subscribe({next: () => { this.notice('Account created. Please sign in with your new username or email.'); this.registration = {name: '', email: '', username: '', password: ''}; this.router.navigateByUrl('/customer-login'); }, error: (e: any) => this.notice(e.error?.message || 'Unable to create your account.', true)}); }
  submitOnboarding() { this.api.post<any>('/account-requests', this.onboarding).subscribe({next: () => { this.notice('Request submitted. Wait for staff approval before creating your account.'); this.onboarding = {name: '', email: '', mobileNumber: '', panNumber: ''}; }, error: (e: any) => this.notice(e.error?.message || 'Unable to submit request.', true)}); }
  loadRequests() { this.fetch('/account-requests'); }
  reviewOnboarding(r: any, status: string) { this.api.patch<any>('/account-requests/' + r.id, {status, comment: ''}).subscribe({next: () => { this.notice('Request ' + status.toLowerCase() + '.'); this.loadRequests(); }, error: (e: any) => this.notice(e.error?.message || 'Unable to review request.', true)}); }
  loadCardApplications(path:string){this.api.get<any[]>(path).subscribe(v=>this.cardRequests=v)} submitCardApplication(){this.api.post<any>('/card-requests',this.cardApplication).subscribe({next:()=>{this.notice('Card request submitted.');this.loadCardApplications('/card-requests/mine')},error:(e:any)=>this.notice(e.error?.message||'Unable to submit request.',true)})} reviewCardApplication(r:any,status:string){this.api.patch<any>('/card-requests/'+r.id,{status,comment:''}).subscribe(()=>{this.notice('Request updated.');this.loadCardApplications('/card-requests')})} approveCardApplication(r:any){this.api.patch<any>('/card-requests/'+r.id,{status:'APPROVED',comment:''}).subscribe(()=>this.router.navigateByUrl('/cards?customerId='+r.customerId+'&cardType='+r.cardType))}
  logout() { this.api.logout(); this.router.navigateByUrl('/'); }
  load() { if (!this.session) return; if (this.path.includes('dashboard')) { this.api.get<any>(this.session.role === 'STAFF' ? '/staff/dashboard' : '/dashboard').subscribe({ next: d => { this.dashboard = d; if(this.session?.role === 'CUSTOMER') this.api.get<any>('/features/score').subscribe(v => this.featureScore = v); const staff = this.session?.role === 'STAFF'; const raw = staff ? [['Total customers', d.totalCustomers], ['Total credit cards', d.totalCards], ['Total merchants', d.totalMerchants], ['Total transactions', d.totalTransactions], ['Active cards', d.activeCards], ['Blocked cards', d.blockedCards], ['Total outstanding', '₹' + d.totalOutstandingAmount], ['Total available credit', '₹' + d.totalAvailableCredit]] : [['Cards', d.totalCards], ['Outstanding', '₹' + d.totalOutstandingAmount], ['Available credit', '₹' + d.totalAvailableCredit]]; this.metrics = raw.map(item => ({label: String(item[0]), value: item[1]})); }, error: () => this.notice('Could not load dashboard.', true) }); return; } if (this.path === '/customers') this.fetch('/customers'); else if(this.path === '/card-request') this.loadCardApplications('/card-requests/mine'); else if(this.path === '/card-requests') this.loadCardApplications('/card-requests'); else if (this.path === '/account-requests') this.loadRequests(); else if (this.path === '/cards') this.fetch('/cards'); else if (this.path === '/my-cards') this.loadOwnCards(); else if (this.path === '/merchants') this.fetch('/merchants'); else if (this.path === '/purchase' || this.path === '/payment') { this.loadOwnCards(); if (this.path === '/purchase') this.api.get<any[]>('/purchase-merchants').subscribe({next: items => this.merchantOptions = items, error: () => this.notice('No merchants are available for purchases yet.', true)}); } else if (this.path === '/transactions' || this.path === '/my-transactions') this.loadTransactions(); else if (this.path === '/statements') { this.fetch('/statements/mine'); this.loadOwnCards(); this.loadStatementTransactions(); } }
  fetch(path: string) { this.api.get<any[]>(path).subscribe({next: items => this.list = items, error: (e: any) => this.notice(e.error?.message || 'Unable to load data.', true)}); }
  loadOwnCards() { this.api.get<any[]>('/cards/mine').subscribe({next: cards => { this.ownCardOptions = cards; if (this.path === '/my-cards') this.list = cards; }, error: (e: any) => this.notice(e.error?.message || 'Unable to load cards.', true)}); }
  loadStatementTransactions() { const month = this.statement.month; if (!month) return; const start = month + '-01'; const date = new Date(start + 'T00:00:00'); const end = new Date(date.getFullYear(), date.getMonth() + 1, 0).toISOString().slice(0, 10); const cardFilter = this.statement.cardId ? '&cardId=' + this.statement.cardId : ''; this.api.get<any[]>('/transactions?from=' + start + '&to=' + end + cardFilter).subscribe({next: transactions => this.statementTransactions = transactions, error: () => this.statementTransactions = []}); }
  notice(message: string, error = false) { this.message = message; this.error = error; }
  lookupCustomer() { this.cardCustomerName = ''; if (!this.card.customerId) return; this.api.get<any>('/customers/' + this.card.customerId).subscribe({next: customer => this.cardCustomerName = customer.name, error: () => this.cardCustomerName = 'Customer not found'}); }
  saveCustomer() { const request = this.customer.id ? this.api.put<any>('/customers/' + this.customer.id, this.customer) : this.api.post<any>('/customers', this.customer); request.subscribe({next: () => { this.notice('Customer saved.'); this.customer = {}; this.showForm = ''; this.fetch('/customers'); }, error: (e: any) => this.notice(e.error?.message || 'Please check the customer details.', true)}); }
  editCustomer(customer: any) { this.customer = {...customer}; this.showForm = 'customer'; }
  saveCard() { this.api.post<any>('/cards', {...this.card, customerId: +this.card.customerId, creditLimit: +this.card.creditLimit}).subscribe({next: () => { this.notice('Card issued successfully.'); this.showForm = ''; this.fetch('/cards'); }, error: (e: any) => this.notice(e.error?.message || 'Please check the card details.', true)}); }
  saveMerchant() { this.api.post<any>('/merchants', this.merchant).subscribe({next: () => { this.notice('Merchant saved.'); this.merchant = {}; this.showForm = ''; this.fetch('/merchants'); }, error: (e: any) => this.notice(e.error?.message || 'Please check the merchant details.', true)}); }
  remove(path: string) { if (confirm('Delete this record?')) this.api.delete(path).subscribe({next: () => { this.notice('Record deleted.'); this.load(); }, error: (e: any) => this.notice(e.error?.message || 'Cannot delete this record.', true)}); }
  toggleCard(card: any) { this.api.patch<any>('/cards/' + card.id + '/status?value=' + (card.status === 'ACTIVE' ? 'BLOCKED' : 'ACTIVE')).subscribe({next: () => { this.notice('Card status updated.'); this.fetch('/cards'); }, error: (e: any) => this.notice(e.error?.message || 'Update failed.', true)}); }
  block(card: any) { this.api.patch<any>('/cards/' + card.id + '/block').subscribe({next: () => { this.notice('Your card has been blocked.'); this.loadOwnCards(); }, error: (e: any) => this.notice(e.error?.message || 'Unable to block card.', true)}); }
  submitTransaction() { const endpoint = this.path === '/purchase' ? '/transactions/purchase' : '/payments'; this.api.post<any>(endpoint, {...this.transaction, amount: +this.transaction.amount}).subscribe({next: tx => { this.notice(tx.status === 'SUCCESS' ? 'Transaction completed successfully.' : 'Transaction failed: ' + tx.failureReason, tx.status !== 'SUCCESS'); this.transaction = {cardNumber: '', merchantId: null, amount: null}; this.loadOwnCards(); }, error: (e: any) => this.notice(e.error?.message || 'Transaction could not be processed.', true)}); }
  loadTransactions() { this.fetch('/transactions'); }
  downloadStatement(statement: any) { this.api.download('/statements/' + statement.id + '/pdf').subscribe({next: pdf => { const url = URL.createObjectURL(pdf); const link = document.createElement('a'); link.href = url; link.download = 'mosaic-vault-statement-' + statement.cardNumber + '-' + statement.periodStart + '.pdf'; link.click(); URL.revokeObjectURL(url); this.notice('PDF statement download started. Check your browser Downloads folder.'); }, error: (e: any) => this.notice(e.error?.message || 'Unable to download the PDF statement.', true)}); }
  generateStatement() { this.api.post<any>('/statements/card/' + this.statement.cardId + '?month=' + this.statement.month).subscribe({next: () => { this.notice('Statement generated.'); this.showForm = ''; this.fetch('/statements/mine'); this.loadStatementTransactions(); }, error: (e: any) => this.notice(e.error?.message || 'Unable to generate statement.', true)}); }
}

export const routes: Routes = [{ path: '**', component: PortalPageComponent }];