spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: system
    password: NewPassword123

    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate.ddl-auto: validate
    defer-datasource-initialization: false
 