package com.bank.portal.service;
import com.bank.portal.domain.*; import com.bank.portal.repository.*; import com.bank.portal.web.ApiDtos.*; import java.math.BigDecimal; import java.time.*; import java.util.*; import java.util.stream.*; import lombok.RequiredArgsConstructor; import org.slf4j.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class BankingService {
 private static final Logger log=LoggerFactory.getLogger(BankingService.class); private final CustomerRepository customers; private final CustomerUserRepository customerUsers; private final StaffUserRepository staffUsers; private final CardRepository cards; private final MerchantRepository merchants; private final TransactionRepository transactions; private final StatementRepository statements;
 private Customer customer(Long id){return customers.findById(id).orElseThrow(()->new IllegalArgumentException("Customer not found"));} private CreditCard card(Long id){return cards.findById(id).orElseThrow(()->new IllegalArgumentException("Card not found"));} private Merchant merchant(Long id){return merchants.findById(id).orElseThrow(()->new IllegalArgumentException("Merchant not found"));}
 public Long customerId(String username){return customerUsers.findByUsername(username).map(u->u.getCustomer().getId()).orElseThrow(()->new IllegalArgumentException("Customer account not found"));}
 public LoginView login(String username){return staffUsers.findByUsername(username).<LoginView>map(u->new LoginView(username,"STAFF",u.getFullName())).or(()->customerUsers.findByUsername(username).map(u->new LoginView(username,"CUSTOMER",u.getCustomer().getName()))).orElseThrow(()->new IllegalArgumentException("Account not found"));}
 public List<CustomerView> customerList(){return customers.findAll().stream().map(this::view).toList();} public CustomerView customerView(Long id){return view(customer(id));}
 @Transactional public CustomerView createCustomer(CustomerRequest r){Customer c=new Customer();copy(c,r);return view(customers.save(c));} @Transactional public CustomerView updateCustomer(Long id,CustomerRequest r){Customer c=customer(id);copy(c,r);return view(c);} @Transactional public void deleteCustomer(Long id){if(cards.findByCustomerId(id).size()>0)throw new IllegalStateException("Cannot delete a customer with cards");customers.delete(customer(id));}
 private void copy(Customer c,CustomerRequest r){c.setName(r.name());c.setEmail(r.email().toLowerCase());c.setMobileNumber(r.mobileNumber());c.setPanNumber(r.panNumber().toUpperCase());} private CustomerView view(Customer c){return new CustomerView(c.getId(),c.getName(),c.getEmail(),c.getMobileNumber(),c.getPanNumber());}
 public List<CardView> allCards(){return cards.findAll().stream().map(this::view).toList();} public List<CardView> ownCards(String username){return cards.findByCustomerId(customerId(username)).stream().map(this::view).toList();} public CardView cardView(Long id,String username,boolean staff){CreditCard c=card(id);own(c,username,staff);return view(c);}
 @Transactional public CardView issue(CardRequest r){Customer c=customer(r.customerId());CreditCard card=new CreditCard();card.setCustomer(c);card.setCardType(r.cardType());card.setCreditLimit(r.creditLimit());card.setAvailableCredit(r.creditLimit());card.setOutstandingAmount(BigDecimal.ZERO);card.setExpiryDate(r.expiryDate());card.setStatus(CardStatus.ACTIVE);card.setCardNumber(nextCardNumber());return view(cards.save(card));}
 @Transactional public CardView updateCard(Long id,CardRequest r){CreditCard c=card(id);if(c.getOutstandingAmount().compareTo(BigDecimal.ZERO)>0&&r.creditLimit().compareTo(c.getOutstandingAmount())<0)throw new IllegalArgumentException("Credit limit cannot be less than outstanding amount");c.setCardType(r.cardType());c.setCreditLimit(r.creditLimit());c.setExpiryDate(r.expiryDate());c.setAvailableCredit(r.creditLimit().subtract(c.getOutstandingAmount()));return view(c);} @Transactional public CardView staffStatus(Long id,CardStatus s){CreditCard c=card(id);c.setStatus(s);return view(c);} @Transactional public CardView blockOwn(Long id,String username){CreditCard c=card(id);own(c,username,false);c.setStatus(CardStatus.BLOCKED);return view(c);}
 private String nextCardNumber(){String digits="4"+String.format("%015d",Math.abs(UUID.randomUUID().getMostSignificantBits())%1_000_000_000_000_000L);return digits.replaceAll("(.{4})(?!$)","$1-");} private void own(CreditCard c,String username,boolean staff){if(!staff&&!c.getCustomer().getId().equals(customerId(username)))throw new IllegalArgumentException("You can access only your own cards");} private CardView view(CreditCard c){return new CardView(c.getId(),c.getCustomer().getId(),c.getCustomer().getName(),c.getCardNumber(),c.getCardType(),c.getCreditLimit(),c.getAvailableCredit(),c.getOutstandingAmount(),c.getExpiryDate(),c.getStatus());}
 public List<MerchantView> merchantList(){return merchants.findAll().stream().map(this::view).toList();} @Transactional public MerchantView createMerchant(MerchantRequest r){Merchant m=new Merchant();copy(m,r);return view(merchants.save(m));} @Transactional public MerchantView updateMerchant(Long id,MerchantRequest r){Merchant m=merchant(id);copy(m,r);return view(m);} @Transactional public void deleteMerchant(Long id){merchants.delete(merchant(id));} private void copy(Merchant m,MerchantRequest r){m.setName(r.name());m.setCategory(r.category());m.setLocation(r.location());} private MerchantView view(Merchant m){return new MerchantView(m.getId(),m.getName(),m.getCategory(),m.getLocation());}
 @Transactional public TransactionView purchase(PurchaseRequest r,String username){CreditCard c=cards.findByCardNumber(r.cardNumber()).orElseThrow(()->new IllegalArgumentException("Card number not found"));own(c,username,false);Merchant m=merchant(r.merchantId());String failure=null;if(c.getStatus()!=CardStatus.ACTIVE)failure="Card is blocked";else if(c.getAvailableCredit().compareTo(r.amount())<0)failure="Insufficient available credit";CardTransaction t=transaction(c,m,r.amount(),TransactionType.PURCHASE,failure);if(failure==null){c.setAvailableCredit(c.getAvailableCredit().subtract(r.amount()));c.setOutstandingAmount(c.getOutstandingAmount().add(r.amount()));log.info("Purchase approved for card {}",c.getId());}else log.info("Purchase declined for card {}: {}",c.getId(),failure);return txView(transactions.save(t));}
 @Transactional public TransactionView pay(PaymentRequest r,String username){CreditCard c=cards.findByCardNumber(r.cardNumber()).orElseThrow(()->new IllegalArgumentException("Card number not found"));own(c,username,false);String failure=c.getOutstandingAmount().compareTo(r.amount())<0?"Payment exceeds outstanding amount":null;CardTransaction t=transaction(c,null,r.amount(),TransactionType.PAYMENT,failure);if(failure==null){c.setOutstandingAmount(c.getOutstandingAmount().subtract(r.amount()));c.setAvailableCredit(c.getAvailableCredit().add(r.amount()));log.info("Payment recorded for card {}",c.getId());}return txView(transactions.save(t));}
 private CardTransaction transaction(CreditCard c,Merchant m,BigDecimal amount,TransactionType type,String failure){CardTransaction t=new CardTransaction();t.setCard(c);t.setMerchant(m);t.setAmount(amount);t.setTransactionType(type);t.setStatus(failure==null?TransactionStatus.SUCCESS:TransactionStatus.FAILED);t.setFailureReason(failure);return t;}
 public List<TransactionView> search(Long cardId,Long customerId,Long merchantId,TransactionType type,TransactionStatus status,LocalDate from,LocalDate to,String username,boolean staff){Long scoped=staff?customerId:customerId(username);return transactions.search(cardId,scoped,merchantId,type,status,from==null?null:from.atStartOfDay(),to==null?null:to.plusDays(1).atStartOfDay()).stream().map(this::txView).toList();} public List<TransactionView> recent(String username){return transactions.findTop8ByCardCustomerIdOrderByTransactionDateDesc(customerId(username)).stream().map(this::txView).toList();} private TransactionView txView(CardTransaction t){Customer c=t.getCard().getCustomer();return new TransactionView(t.getId(),c.getId(),c.getName(),t.getCard().getCardNumber(),t.getMerchant()==null?null:t.getMerchant().getName(),t.getAmount(),t.getTransactionType(),t.getStatus(),t.getFailureReason(),t.getTransactionDate());}
 public DashboardView staffDashboard(){List<CreditCard> all=cards.findAll();return new DashboardView(customers.count(),all.size(),merchants.count(),transactions.count(),cards.countByStatus(CardStatus.ACTIVE),cards.countByStatus(CardStatus.BLOCKED),sum(all,CreditCard::getOutstandingAmount),sum(all,CreditCard::getAvailableCredit),List.of(),transactions.findTop8ByOrderByTransactionDateDesc().stream().map(this::txView).toList());} public DashboardView customerDashboard(String username){List<CreditCard> own=cards.findByCustomerId(customerId(username));return new DashboardView(0,own.size(),0,0,0,0,sum(own,CreditCard::getOutstandingAmount),sum(own,CreditCard::getAvailableCredit),own.stream().map(this::view).toList(),recent(username));} private BigDecimal sum(List<CreditCard> all,java.util.function.Function<CreditCard,BigDecimal> f){return all.stream().map(f).reduce(BigDecimal.ZERO,BigDecimal::add);}
 @Transactional public StatementView statement(Long cardId,YearMonth month,String username,boolean staff){CreditCard c=card(cardId);own(c,username,staff);LocalDate start=month.atDay(1),end=month.atEndOfMonth();MonthlyStatement s=statements.findByCardIdAndPeriodStart(cardId,start).orElseGet(MonthlyStatement::new);List<CardTransaction> all=transactions.findByCardCustomerIdOrderByTransactionDateDesc(c.getCustomer().getId()).stream().filter(t->t.getCard().getId().equals(cardId)&&t.getStatus()==TransactionStatus.SUCCESS).toList();BigDecimal purchases=total(all,TransactionType.PURCHASE,start,end),payments=total(all,TransactionType.PAYMENT,start,end);BigDecimal opening=all.stream().filter(t->t.getTransactionDate().toLocalDate().isBefore(start)).map(t->t.getTransactionType()==TransactionType.PURCHASE?t.getAmount():t.getAmount().negate()).reduce(BigDecimal.ZERO,BigDecimal::add);s.setCustomer(c.getCustomer());s.setCard(c);s.setPeriodStart(start);s.setPeriodEnd(end);s.setOpeningBalance(opening);s.setPurchases(purchases);s.setPayments(payments);s.setClosingBalance(opening.add(purchases).subtract(payments));return statementView(statements.save(s));} private BigDecimal total(List<CardTransaction> tx,TransactionType type,LocalDate start,LocalDate end){return tx.stream().filter(t->t.getTransactionType()==type&&!t.getTransactionDate().toLocalDate().isBefore(start)&&!t.getTransactionDate().toLocalDate().isAfter(end)).map(CardTransaction::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);} public List<StatementView> ownStatements(String username){return statements.findByCustomerIdOrderByPeriodStartDesc(customerId(username)).stream().map(this::statementView).toList();} private StatementView statementView(MonthlyStatement s){return new StatementView(s.getId(),s.getCard().getId(),s.getCard().getCardNumber(),s.getPeriodStart(),s.getPeriodEnd(),s.getOpeningBalance(),s.getPurchases(),s.getPayments(),s.getClosingBalance());}
}
