package com.bank.portal.service;
import com.bank.portal.domain.*; import com.bank.portal.repository.*; import com.bank.portal.web.ApiDtos.*; import java.math.*; import java.time.*; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class FeatureService { private final CustomerUserRepository users; private final CardRepository cards; private final CreditLimitRequestRepository requests; private final CreditScoreEventRepository events; private final StatementRepository statements; private final TransactionRepository transactions; private final CreditHealthService score;
 private Customer customer(String u){return users.findByUsernameOrCustomerEmail(u,u).orElseThrow(()->new IllegalArgumentException("Customer not found")).getCustomer();} private CreditCard card(Long id){return cards.findById(id).orElseThrow(()->new IllegalArgumentException("Card not found"));}
 public ScoreView score(String username){Customer c=customer(username);return new ScoreView(c.getCreditHealthScore(),rating(c.getCreditHealthScore()),c.getRewardPoints(),c.getCashbackBalance(),events.findByCustomerIdOrderByEventDateDescCreatedAtDesc(c.getId()).stream().map(e->new ScoreEventView(e.getEventType().name(),e.getPoints(),e.getDescription(),e.getEventDate())).toList());} private String rating(int s){return s>=850?"Exceptional":s>=800?"Excellent":s>=750?"Very Good":s>=700?"Good":s>=650?"Fair":s>=600?"Poor":"Very Poor";}
 @Transactional public LimitRequestView request(String username,LimitRequestInput r){Customer c=customer(username);CreditCard card=card(r.cardId());if(!card.getCustomer().getId().equals(c.getId()))throw new IllegalArgumentException("Only your own card can be requested");if(r.requestedLimit().compareTo(card.getCreditLimit())<=0)throw new IllegalArgumentException("Requested limit must exceed current limit");if(requests.existsByCardIdAndStatus(card.getId(),CreditLimitRequestStatus.PENDING))throw new IllegalStateException("A pending request already exists");CreditLimitRequest q=new CreditLimitRequest();q.setCustomer(c);q.setCard(card);q.setCurrentLimit(card.getCreditLimit());q.setRequestedLimit(r.requestedLimit());q.setReason(r.reason());q.setStatus(CreditLimitRequestStatus.PENDING);return view(requests.save(q));}
 public List<LimitRequestView> mine(String u){return requests.findByCustomerIdOrderByCreatedAtDesc(customer(u).getId()).stream().map(this::view).toList();} public List<LimitRequestView> pending(){return requests.findByStatusOrderByCreatedAtAsc(CreditLimitRequestStatus.PENDING).stream().map(this::view).toList();}
 @Transactional public LimitRequestView review(Long id,ReviewInput r,String staff){CreditLimitRequest q=requests.findById(id).orElseThrow(()->new IllegalArgumentException("Request not found"));if(q.getStatus()!=CreditLimitRequestStatus.PENDING)throw new IllegalStateException("Request already reviewed");q.setStatus(r.status());q.setReviewedBy(staff);q.setReviewedAt(LocalDateTime.now());q.setReviewComment(r.comment());if(r.status()==CreditLimitRequestStatus.APPROVED){CreditCard c=q.getCard();BigDecimal delta=q.getRequestedLimit().subtract(c.getCreditLimit());c.setCreditLimit(q.getRequestedLimit());c.setAvailableCredit(c.getAvailableCredit().add(delta));score.apply(q.getCustomer(),c,CreditScoreEventType.CREDIT_LIMIT_INCREASE,10,"LIMIT-"+q.getId(),"Bank approved credit limit increase");}return view(q);}
 @Transactional public int applyLateFees(){int count=0;for(MonthlyStatement s:statements.findAll())if(s.getLateFeeApplied()==0&&s.getDueDate()!=null&&s.getDueDate().isBefore(LocalDate.now())&&s.getClosingBalance().compareTo(BigDecimal.ZERO)>0){BigDecimal fee=s.getClosingBalance().multiply(new BigDecimal(".02")).max(new BigDecimal("250"));CreditCard c=s.getCard();c.setOutstandingAmount(c.getOutstandingAmount().add(fee));c.setAvailableCredit(c.getAvailableCredit().subtract(fee));CardTransaction t=new CardTransaction();t.setCard(c);t.setAmount(fee);t.setTransactionType(TransactionType.LATE_FEE);t.setStatus(TransactionStatus.SUCCESS);t.setFailureReason("Late payment fee");transactions.save(t);s.setLateFeeApplied(1);score.apply(s.getCustomer(),c,CreditScoreEventType.LATE_PAYMENT,-20,"LATE-"+s.getId(),"Late payment after statement due date");count++;}return count;}
 private LimitRequestView view(CreditLimitRequest q){return new LimitRequestView(q.getId(),q.getCard().getId(),q.getCard().getCardNumber(),q.getCurrentLimit(),q.getRequestedLimit(),q.getReason(),q.getStatus().name(),q.getReviewedBy(),q.getReviewComment());}}
