package com.bank.portal.service;

import com.bank.portal.domain.CardTransaction;
import com.bank.portal.domain.MonthlyStatement;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.springframework.stereotype.Component;

/**
 * Creates a compact, dependency-free PDF statement.  The document uses the
 * standard PDF Helvetica font so it can be downloaded and opened by any PDF
 * reader without storing a generated file on the server.
 */
@Component
public class StatementPdfGenerator {
    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("dd MMM uuuu");
    private static final DateTimeFormatter DATE_TIME = DateTimeFormatter.ofPattern("dd MMM uuuu HH:mm");
    private static final int ACTIVITY_LINES_PER_PAGE = 29;

    public byte[] generate(MonthlyStatement statement, List<CardTransaction> activity) {
        List<List<CardTransaction>> activityPages = partition(activity, ACTIVITY_LINES_PER_PAGE);
        int pageCount = 1 + activityPages.size();
        int objectCount = 3 + (pageCount * 2);
        long[] offsets = new long[objectCount + 1];
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        write(output, "%PDF-1.4\n%âãÏÓ\n");
        writeObject(output, offsets, 1, "<< /Type /Catalog /Pages 2 0 R >>");

        StringBuilder kids = new StringBuilder();
        for (int page = 0; page < pageCount; page++) {
            kids.append(4 + (page * 2)).append(" 0 R ");
        }
        writeObject(output, offsets, 2, "<< /Type /Pages /Kids [" + kids + "] /Count " + pageCount + " >>");
        writeObject(output, offsets, 3, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

        for (int page = 0; page < pageCount; page++) {
            int pageObject = 4 + (page * 2);
            int contentObject = pageObject + 1;
            String contents = page == 0
                    ? summaryPage(statement, activity.size())
                    : activityPage(statement, activityPages.get(page - 1), page, pageCount - 1);
            writeObject(output, offsets, pageObject,
                    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents " + contentObject + " 0 R >>");
            writeStreamObject(output, offsets, contentObject, contents);
        }

        long xrefOffset = output.size();
        write(output, "xref\n0 " + (objectCount + 1) + "\n0000000000 65535 f \n");
        for (int object = 1; object <= objectCount; object++) {
            write(output, String.format(Locale.ROOT, "%010d 00000 n \n", offsets[object]));
        }
        write(output, "trailer\n<< /Size " + (objectCount + 1) + " /Root 1 0 R >>\nstartxref\n" + xrefOffset + "\n%%EOF");
        return output.toByteArray();
    }

    private String summaryPage(MonthlyStatement statement, int activityCount) {
        List<String> lines = new ArrayList<>();
        lines.add("MOSAIC VAULT");
        lines.add("Credit Card Monthly Statement");
        lines.add("");
        lines.add("Customer: " + statement.getCustomer().getName());
        lines.add("Card number: " + statement.getCard().getCardNumber());
        lines.add("Statement period: " + DATE.format(statement.getPeriodStart()) + " to " + DATE.format(statement.getPeriodEnd()));
        lines.add("Payment due date: " + DATE.format(statement.getDueDate() == null ? statement.getPeriodEnd() : statement.getDueDate()));
        lines.add("");
        lines.add("Opening balance: " + money(statement.getOpeningBalance()));
        lines.add("Purchases: " + money(statement.getPurchases()));
        lines.add("Payments received: " + money(statement.getPayments()));
        lines.add("Closing balance: " + money(statement.getClosingBalance()));
        lines.add("");
        lines.add("Account activity records in this period: " + activityCount);
        lines.add(activityCount == 0 ? "No card activity was recorded during this statement period." : "Detailed activity follows on the next page.");
        lines.add("");
        lines.add("This document was generated by Mosaic Vault. Please retain it for your records.");
        return textPage(lines, 18, 34);
    }

    private String activityPage(MonthlyStatement statement, List<CardTransaction> activity, int pageNumber, int activityPageCount) {
        List<String> lines = new ArrayList<>();
        lines.add("MOSAIC VAULT - Statement Activity");
        lines.add("Card " + statement.getCard().getCardNumber() + " | " + DATE.format(statement.getPeriodStart()) + " to " + DATE.format(statement.getPeriodEnd()));
        lines.add("Activity page " + pageNumber + " of " + activityPageCount);
        lines.add("");
        lines.add("Date and time | Type | Merchant | Amount | Status");
        lines.add("--------------------------------------------------------------------------------");
        for (CardTransaction transaction : activity) {
            String merchant = transaction.getMerchant() == null ? "-" : transaction.getMerchant().getName();
            String line = DATE_TIME.format(transaction.getTransactionDate()) + " | "
                    + transaction.getTransactionType() + " | " + merchant + " | "
                    + money(transaction.getAmount()) + " | " + transaction.getStatus();
            lines.add(line);
        }
        return textPage(lines, 13, 16);
    }

    private String textPage(List<String> lines, int titleSize, int leading) {
        StringBuilder contents = new StringBuilder("BT\n/F1 ").append(titleSize).append(" Tf\n50 790 Td\n");
        for (int index = 0; index < lines.size(); index++) {
            if (index == 1) {
                contents.append("/F1 12 Tf\n");
            }
            contents.append('(').append(escape(lines.get(index))).append(") Tj\n");
            contents.append("0 -").append(leading).append(" Td\n");
        }
        contents.append("ET");
        return contents.toString();
    }

    private List<List<CardTransaction>> partition(List<CardTransaction> activity, int size) {
        List<List<CardTransaction>> pages = new ArrayList<>();
        for (int start = 0; start < activity.size(); start += size) {
            pages.add(activity.subList(start, Math.min(start + size, activity.size())));
        }
        return pages;
    }

    private String money(BigDecimal amount) {
        return "INR " + amount.setScale(2).toPlainString();
    }

    private String escape(String value) {
        return value.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
                .replaceAll("[^\\x20-\\x7E]", "?");
    }

    private void writeObject(ByteArrayOutputStream output, long[] offsets, int id, String body) {
        offsets[id] = output.size();
        write(output, id + " 0 obj\n" + body + "\nendobj\n");
    }

    private void writeStreamObject(ByteArrayOutputStream output, long[] offsets, int id, String contents) {
        byte[] bytes = contents.getBytes(StandardCharsets.ISO_8859_1);
        offsets[id] = output.size();
        write(output, id + " 0 obj\n<< /Length " + bytes.length + " >>\nstream\n");
        output.writeBytes(bytes);
        write(output, "\nendstream\nendobj\n");
    }

    private void write(ByteArrayOutputStream output, String value) {
        output.writeBytes(value.getBytes(StandardCharsets.ISO_8859_1));
    }
}
