-- Run once in the Oracle application schema after V4.
ALTER TABLE customer_users ADD (avatar_key VARCHAR2(32) DEFAULT 'mosaic-fox' NOT NULL);

CREATE TABLE gateway_payment_orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  card_id NUMBER NOT NULL,
  gateway_order_id VARCHAR2(100) NOT NULL,
  gateway_payment_id VARCHAR2(100),
  amount NUMBER(15,2) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT uq_gateway_payment_order UNIQUE (gateway_order_id),
  CONSTRAINT fk_gateway_payment_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_gateway_payment_card FOREIGN KEY (card_id) REFERENCES credit_cards(id)
);
CREATE INDEX idx_gateway_payment_customer ON gateway_payment_orders(customer_id);
CREATE INDEX idx_gateway_payment_status ON gateway_payment_orders(status);
