package com.bank.portal.web;
import com.bank.portal.domain.*; import jakarta.validation.constraints.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
public final class ApiDtos { private ApiDtos(){}
 public record CustomerRequest(@NotBlank String name,@Email @NotBlank String email,@NotBlank @Pattern(regexp="[0-9]{10}") String mobileNumber,@NotBlank @Pattern(regexp="[A-Z]{5}[0-9]{4}[A-Z]") String panNumber){} public record CustomerView(Long id,String name,String email,String mobileNumber,String panNumber){}
 public record CardRequest(@NotNull Long customerId,@NotNull CardType cardType,@NotNull @DecimalMin("1.00") BigDecimal creditLimit,@NotNull @Future LocalDate expiryDate){} public record CardView(Long id,Long customerId,String customerName,String cardNumber,CardType cardType,BigDecimal creditLimit,BigDecimal availableCredit,BigDecimal outstandingAmount,LocalDate expiryDate,CardStatus status){}
 public record MerchantRequest(@NotBlank String name,@NotBlank String category,@NotBlank String location){} public record MerchantView(Long id,String name,String category,String location){}
 public record PurchaseRequest(@NotBlank String cardNumber,@NotNull Long merchantId,@NotNull @DecimalMin("0.01") BigDecimal amount){} public record PaymentRequest(@NotBlank String cardNumber,@NotNull @DecimalMin("0.01") BigDecimal amount){}
 public record TransactionView(Long id,Long customerId,String customerName,String cardNumber,String merchant,BigDecimal amount,TransactionType transactionType,TransactionStatus status,String failureReason,LocalDateTime transactionDate){}
 public record DashboardView(long totalCustomers,long totalCards,long totalMerchants,long totalTransactions,long activeCards,long blockedCards,BigDecimal totalOutstandingAmount,BigDecimal totalAvailableCredit,List<CardView> cards,List<TransactionView> recentTransactions){}
 public record StatementView(Long id,Long cardId,String cardNumber,LocalDate periodStart,LocalDate periodEnd,LocalDate dueDate,BigDecimal openingBalance,BigDecimal purchases,BigDecimal payments,BigDecimal closingBalance){} public record CardTypeCustomerCount(String cardType,long customerCount){} public record MonthlyTransactionCount(int month,String label,long transactionCount){} public record AdminAnalyticsView(List<CardTypeCustomerCount> cardTypeCustomers,List<MonthlyTransactionCount> monthlyTransactions){} public record SignupRequest(@NotBlank String name,@Email @NotBlank String email,@NotBlank @Size(min=3,max=80) String username,@NotBlank @Size(min=8,max=72) String password,@NotBlank @Pattern(regexp="mosaic-(fox|owl|cat|panda|rocket|flower)") String avatarKey){} public record CardApplicationInput(@NotNull CardType cardType){} public record CardApplicationView(Long id,Long customerId,String customerName,CardType cardType,String status,String reviewComment){} public record CardApplicationReview(@NotNull CustomerCardRequestStatus status,String comment){} public record OnboardingRequestInput(@NotBlank String name,@Email @NotBlank String email,@NotBlank @Pattern(regexp="[0-9]{10}") String mobileNumber,@NotBlank @Pattern(regexp="[A-Z]{5}[0-9]{4}[A-Z]") String panNumber){} public record OnboardingRequestView(Long id,String name,String email,String mobileNumber,String panNumber,String status,String reviewComment){} public record OnboardingReviewInput(@NotNull OnboardingRequestStatus status,String comment){} public record ScoreView(Integer score,String rating,Integer rewardPoints,BigDecimal cashbackBalance,List<ScoreEventView> events){} public record ScoreEventView(String eventType,Integer points,String description,LocalDate eventDate){} public record LimitRequestInput(@NotNull Long cardId,@NotNull @DecimalMin("1.00") BigDecimal requestedLimit,@NotBlank String reason){} public record LimitRequestView(Long id,Long cardId,String cardNumber,BigDecimal currentLimit,BigDecimal requestedLimit,String reason,String status,String reviewedBy,String reviewComment){} public record ReviewInput(@NotNull CreditLimitRequestStatus status,String comment){} public record GatewayOrderRequest(@NotBlank String cardNumber,@NotNull @DecimalMin("0.01") BigDecimal amount){} public record GatewayOrderView(String orderId,String keyId,long amountPaise,String currency){} public record GatewayPaymentVerification(@NotBlank String orderId,@NotBlank String paymentId,@NotBlank String signature){} public record LoginView(String username,String role,String displayName,String avatarKey){} public record MessageView(String message){}
}
